// <auto-generated />
using System;
using EmployeeEvaluationAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeEvaluationAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210826141217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.Property<int?>("done_by")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("done_for")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvaluationID");

                    b.HasIndex("done_by");

                    b.HasIndex("done_for");

                    b.ToTable("Evaluation");
                });

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Evaluation", b =>
                {
                    b.HasOne("EmployeeEvaluationAPI.Models.Employee", "By")
                        .WithMany()
                        .HasForeignKey("done_by");

                    b.HasOne("EmployeeEvaluationAPI.Models.Employee", "For")
                        .WithMany()
                        .HasForeignKey("done_for");

                    b.Navigation("By");

                    b.Navigation("For");
                });
#pragma warning restore 612, 618
        }
    }
}
