// <auto-generated />
using EmployeeEvaluationAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeEvaluationAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20210827121511_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = -1,
                            Age = 22,
                            Name = "Fadi",
                            Rating = 0.0
                        },
                        new
                        {
                            EmployeeID = -2,
                            Age = 30,
                            Name = "Baha",
                            Rating = 0.0
                        },
                        new
                        {
                            EmployeeID = -3,
                            Age = 26,
                            Name = "Joseph",
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ByEmployeeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("done_by");

                    b.Property<int>("ForEmployeeID")
                        .HasColumnType("INTEGER")
                        .HasColumnName("done_for");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER")
                        .HasColumnName("value");

                    b.HasKey("EvaluationID");

                    b.HasIndex("ByEmployeeID");

                    b.HasIndex("ForEmployeeID");

                    b.ToTable("Evaluations");

                    b.HasData(
                        new
                        {
                            EvaluationID = -1,
                            ByEmployeeID = -1,
                            ForEmployeeID = -2,
                            Value = 80
                        },
                        new
                        {
                            EvaluationID = -2,
                            ByEmployeeID = -2,
                            ForEmployeeID = -3,
                            Value = 90
                        },
                        new
                        {
                            EvaluationID = -3,
                            ByEmployeeID = -3,
                            ForEmployeeID = -1,
                            Value = 80
                        });
                });

            modelBuilder.Entity("EmployeeEvaluationAPI.Models.Evaluation", b =>
                {
                    b.HasOne("EmployeeEvaluationAPI.Models.Employee", "ByEmployee")
                        .WithMany()
                        .HasForeignKey("ByEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeEvaluationAPI.Models.Employee", "ForEmployee")
                        .WithMany()
                        .HasForeignKey("ForEmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ByEmployee");

                    b.Navigation("ForEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
